diplomOriginal/Controllers/UserCabinetController.cs
using diplomOriginal.Login;
using diplomOriginal.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Text;

namespace diplomOriginal.Controllers
{
    public class UserCabinetController : Controller
    {
        public ActionResult Index()
        {
            var user = HttpContext.User.Identity?.IsAuthenticated;
            if (user is not null && user.Value)
            {
                return View();
            } else
            {
                return Redirect("/login");
            }
        }

        [HttpPost]
        public async Task<IActionResult> ChangeName(string newName)
        {
            TempData["ErrorMessage"] = null;

            LoginViewModel vm = new LoginViewModel() { Email = HttpContext.User.FindFirst(ClaimTypes.Email)?.Value ?? "_" };
            if (Database.ChangeAccountName(vm, newName).Result)
            {
                await LoginManager.Logout(HttpContext);
                return Redirect("/login");
            }

            TempData["ErrorMessage"] = "Ошибка при изменении имени, попробуйте еще раз";
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult ChangePassword(string newPassword)
        {
            TempData["ErrorMessage"] = null;
            TempData["SuccessMessage"] = null;

            LoginViewModel vm = new LoginViewModel() { Email = HttpContext.User.FindFirst(ClaimTypes.Email)?.Value ?? "_" };
            if (Database.ChangeAccountPassword(vm, newPassword).Result)
            {
                // Stub variable, value doesnt affect anything
                TempData["SuccessMessage"] = "Пароль успешно изменен"; // Password changed
                return RedirectToAction("Index");
            }

            TempData["ErrorMessage"] = "Ошибка при изменении имени, свяжитесь с администратором";
            return RedirectToAction("Index");
        }
    }
}

diplomOriginal/Views/UserCabinet/Index.cshtml
@using diplomOriginal.Login;
@{
	ViewData["Title"] = "Личный кабинет";
}

<div class="container-xl px-4 py-5 my-5">
    <h2 class="display-5 fw-bold text-body-emphasis">Добро пожаловать, @(Context.User.Identity?.Name ?? "No name found, contact to administrator")</h2>

    @if ((Context.User.FindFirst(System.Security.Claims.ClaimTypes.Role)?.Value ?? "_").Equals(Role.ADMIN.ToString()))
    {
        <strong class="text-body-emphasis">Вы администратор</strong>
    }

    <hr class="mt-0 mb-4">
    <div class="row mx-auto">
        @if (!string.IsNullOrEmpty(TempData["ErrorMessage"]?.ToString() ?? null))
        {
            <strong class="text-danger">@TempData["ErrorMessage"]</strong>
            <hr />
        }

        <!-- Change info form -->
        <div class="col-lg-6 mx-auto">
            <div class="card mb-4 mx-auto">
                <div class="card-header">Изменить информацию об аккаунте</div>
                <div class="card-body">
                    <form asp-controller="UserCabinet" asp-action="ChangeName" method="post">
                        <!-- Form Username-->
                        <div class="mb-3">
                            <label class="small mb-1" for="enter-name-here">Имя на сайте</label>
                            <input required class="form-control" name="newName" id="enter-name-here" type="text" placeholder="Введите свое имя" value="@(Context.User.Identity?.Name ?? "Error")">
                        </div>
                        <!-- Save Button-->
                        <button class="btn btn-primary" type="submit">Сохранить изменения</button>
                    </form>
                </div>
            </div>
        </div>

        <!-- Disable button if passwords do not match -->
        <script>
            function OnPasswordsMatch() {
                var result = checkFieldsByName(document.getElementById("change-password-form"), 'inp_pass1_cabinet', 'inp_pass2_cabinet');
                document.getElementById('change-password-button').disabled = !result;
            }
        </script>

        <!-- Change password form -->
        <div class="col-lg-6 mx-auto">
            <div class="card mb-4 mx-auto">
                <div class="card-header">Изменить пароль</div>
                @if (!string.IsNullOrEmpty(TempData["SuccessMessage"]?.ToString() ?? null))
                {
                    // TempData shows strange results so if success message is not null hardcode the message
                    <script>alert("Пароль успешно изменен")</script>
                }
                <div class="card-body">
                    <form asp-controller="UserCabinet" asp-action="ChangePassword" id="change-password-form">
                        <!-- Form Password-->
                        <div class="mb-3">
                            <label class="small mb-1" for="inp_pass1_cabinet">Введите новый пароль</label>
                            <input required onkeyup="OnPasswordsMatch();" class="form-control" id="inp_pass1_cabinet" name="newPassword" type="password" placeholder="Введите новый пароль">
                        </div>
                        <!-- Form New Password-->
                        <div class="mb-3">
                            <label class="small mb-1" for="inp_pass2_cabinet">Повторите новый пароль</label>
                            <input required onkeyup="OnPasswordsMatch();" class="form-control" id="inp_pass2_cabinet" type="password" placeholder="Повторите новый пароль">
                        </div>
                        <div class="checkbox mb-3">
                            <label>
                                <input type="checkbox" onclick="ShowPassword('inp_pass1_cabinet');ShowPassword('inp_pass2_cabinet')" value="remember-me"> Показать пароль
                            </label>
                        </div>
                        <!-- Save Button-->
                        <button class="btn btn-primary" id="change-password-button" disabled type="submit">Сохранить изменения</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>